/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  env: {
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_AWS_REGION: process.env.NEXT_PUBLIC_AWS_REGION,
    NEXT_PUBLIC_COGNITO_USER_POOL_ID: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID,
    NEXT_PUBLIC_COGNITO_CLIENT_ID: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
    NEXT_PUBLIC_COGNITO_DOMAIN: process.env.NEXT_PUBLIC_COGNITO_DOMAIN,
    NEXT_PUBLIC_COGNITO_SIGN_IN_REDIRECT_URIS: process.env.NEXT_PUBLIC_COGNITO_SIGN_IN_REDIRECT_URIS,
    NEXT_PUBLIC_COGNITO_SIGN_OUT_REDIRECT_URIS: process.env.NEXT_PUBLIC_COGNITO_SIGN_OUT_REDIRECT_URIS
  }
};

export default nextConfig;
